CORRIDORS = [
    {"name": "Airport New South Road", "lat": 13.02752, "lng": 77.63353},
    {"name": "Bannerghata Road", "lat": 12.89638, "lng": 77.59788},
    {"name": "Bellary Road 1", "lat": 13.0168, "lng": 77.5864},
    {"name": "Bellary Road 2", "lat": 13.10596, "lng": 77.60327},
    {"name": "CBD 1", "lat": 12.98102, "lng": 77.60682},
    {"name": "CBD 2", "lat": 12.98331, "lng": 77.59505},
    {"name": "Hennur Main Road", "lat": 13.05115, "lng": 77.62619},
    {"name": "Hosur Road", "lat": 12.91547, "lng": 77.62466},
    {"name": "IRR(Thanisandra road)", "lat": 12.93751, "lng": 77.62694},
    {"name": "Magadi Road", "lat": 12.98506, "lng": 77.52334},
    {"name": "Mysore Road", "lat": 12.95779, "lng": 77.56365},
    {"name": "ORR East 1", "lat": 12.92831, "lng": 77.66913},
    {"name": "ORR East 2", "lat": 12.97583, "lng": 77.69603},
    {"name": "ORR North 1", "lat": 13.02455, "lng": 77.63744},
    {"name": "ORR North 2", "lat": 13.04193, "lng": 77.55882},
    {"name": "ORR West 1", "lat": 12.92084, "lng": 77.55913},
    {"name": "Old Airport Road", "lat": 12.95887, "lng": 77.66185},
    {"name": "Old Madras Road", "lat": 12.98091, "lng": 77.62932},
    {"name": "Tumkur Road", "lat": 13.03146, "lng": 77.53366},
    {"name": "Varthur Road", "lat": 12.95655, "lng": 77.71594},
    {"name": "West of Chord Road", "lat": 12.98297, "lng": 77.54634},
]

ZONES = [
    "Central Zone 1", "Central Zone 2", "East Zone 1", "East Zone 2",
    "North Zone 1", "North Zone 2", "South Zone 1", "South Zone 2",
    "West Zone 1", "West Zone 2",
]

JUNCTIONS = [
    "17th Mn 1st Crs Aishwarya Stores Jn", "27th Cross Jayanagar(Ganapathi Temple)",
    "28thMainJayanagarJunc", "29thMainRdBTM LayoutJunc", "5thMainHSR",
    "5thMainRPC Layout-Vijayanagar", "A S CharStreet-MysoreRdJunc", "ASC Junction",
    "AdugodiJunc", "AgaraJunction", "AnandRaoJunction", "AnepalyaJunc",
    "AnilKumbleCircle", "AnjaneyaTempleJunc", "ArakereGateJunc", "Arbindo Circle",
    "Arts&CraftsCircle", "AshirwadamCircle", "Ashoknagar Junction(ShoolayCircle)",
    "AttiguppeCircleJunction", "AyyappaTempleJunc", "BDA Junctio-Koramangala",
    "BEL Circle", "BEML GateJunc(SuranjandasRd)", "BHEL Gate",
    "BM ShriJunc(CMH-100FtRd)Junc", "BMTCJunction-K H Road", "BTM16thMain-ORR Junc",
    "BagalakunteCrossJunction", "BagalurCrossJunc", "Bamboobazar(Shivajinagar)",
    "BanashankariBusStandJunc", "BangaloreBodyBuildersJunc", "Basappa Circle Junction",
    "BasavamantapaJunc-Dr RajkumarRd", "BasaweshwaraCircle",
    "Basveshwarnagar 8th main Junction", "Batrayanapura(Amrutahalli)Junction",
    "BegumMahalJunc", "Bellandur Junction, Outer ring road", "BhadrappaLayout",
    "BhashyamCircle", "BhashyamCircle-SadashivNagar", "BigBazaar(Whitefield)Junc",
    "BigBazaarJunction(OldMadrasRd)", "BilekahalliJunc", "BinnyMillJunction",
    "BiryandCircle", "BloodBankCircle", "Bommanahalli", "BommanahalliJunc",
    "BommasandraJunc", "CRPF Gate", "CTIJunction", "CarmelSchoolJunc",
    "CentralJailJunc", "ChalukyanCircle", "ChamrajpetCircleJunc", "ChandniChowk",
    "ChikkabettahalliJunc", "ChurchStreetJunc", "CityCorpOfficeJunc",
    "CoronationParkJunc", "DRDO Gate(BellandurBridgeJunc)", "DRDOJunc",
    "DevarajUrsRdJunc", "Dodda AlamaraCentreJunc", "DoddabommasandraJunc",
    "DomlurFlyoverJunc", "DoubleRoad-SankeyCross", "ElectricityOfficeJunc",
    "EntrepreneurCircle", "EveningTechParkJunc", "FoodWorldJunc(KodigehalliCross)",
    "FreedomParkJunc", "GHPSJunc", "GN Multispeciality HospitalJunc",
    "GaneshTempleJunc(BasavanagudiRd)", "GanigarpetJunc", "GargeshwariJunc",
    "GovtHospitalJunc", "GramataraJunc", "HAL OldAirportJunc",
    "HBCSocietyJunc-SadashivNagar", "HMMCJunc", "HanumanthNagarJunc",
    "HaraporaJunc", "HebbalFlyoverJunc", "HebbalParkJunc", "HennurCrossJunc",
    "HennurMainRd-BanaswadijuncJunc", "HimayatSagarLakeJunc",
    "HoramavuAgara Main Junc", "HoramavuSignalJunction",
    "HorsleyRd-ChamrajpetcircleJunc", "HosurRd-ManyataJunc", "HosurRoad-BTM2ndStageJunc",
    "HSR LayoutSignalJunc", "IIMBJunc", "ITIJunc", "IimgColonyCircle",
    "IndirangarFlyoverJunc", "JC Rd Cross", "JMITJunc", "JPNagarCircle",
    "JalahallicrossJunc", "JambuSavariDharmaJunc", "JayamahalExtensionJunc",
    "JayanagaRajendraNagarJunc", "JayanagaRajendraNagaraJunc",
    "KHBColony(Basavanagudi)Junc", "KMFCircleJunc", "KRCircleJunc",
    "KRPuraSignalBridge", "KSRTCLayoutJunc", "KSTDCJunc", "KalenaAgraharaJunc",
    "KamakshipalyaJunc", "KanakadasaJunc", "KangeriJunc", "KengariBusStandJunc",
    "KhodigehalliJunc", "KodigehalliCrossJunc", "KoramangaJunc",
    "KoramangalaCrossJunc", "KoramangalaInnerRingRdJunc", "LMIJunc",
    "LalbaghMainGateJunc", "LottegollahalliJunc", "MJunction",
    "MKK Rd-Pipeline Rd Junc", "MadhavanparkJunc", "MadiwalaCrossJunc",
    "MagadiRdCrossJunc", "MahalakshmilayoutCrossJunc", "MajesticJunc",
    "MalleshwarmCircle", "MalleswarmRailwaygateJunc", "MarthahalliJunc",
    "MathikaJunc", "MattikereJunc", "MedicalCollegeJunc", "MinyurJunc",
    "MsRamannaCircleJunc", "MysoreRd-RingRdJunc(Nayandanahallii)",
    "NLCRoadJunc", "NTCJunc", "NagarBhaviCrossJunc", "NagasandraJunc",
    "NagawaraCrossJunc", "NavarangCircle", "NearBMTCJunc",
    "NearINBOXPrimeJunc(WhitefieldRd)", "NearToShankarpuramSignal",
    "NovatelHotelJunction", "OldMadrasRd-HadosseriJunc", "OldMadrasRd-HoramavuJunc",
    "PTPNagarJunc", "PeeenyaIndustrialAreaJunc", "PeenyaJunc",
    "PeenyaMainGateJunc", "PeenyaRailwayCrossJunc", "PoojaSweetJunc",
    "QatarCircle", "QueensStatueCircle", "QuincyCrossJunc",
    "RMVExtensionJunc", "RajakumarRoadJunc", "RajajinagarcircleJunc",
    "RajajinarCircle", "RamaswamyCircle", "RashtrikavijayCircle",
    "RathnaVilasBuildingJunc", "RingRoadJunc(Nayandanahalli)",
    "SKCircleJunc", "SSPuramCircle", "SadashivanagarmainJunc",
    "SaikrishnaJunc", "SampangiRamaTempleJunc", "SankeyCrossJunc",
    "SanthaJunc", "SarakiJunc", "ShakarabhoomiCrossJunc",
    "ShanthinagarBusStandJunc", "ShettyCircle", "ShivajiNagarBusStandJunc",
    "SirigereJunc", "SriramapuraMainJunc", "SubhashnagarcircleJunc",
    "SumanahallicrossJunc", "TKJunction", "TParkJunc",
    "TatagunnihosahallicrossJunc", "TavarekereMainJunc", "TinFactoryJunc",
    "TridentHotelJunc", "TumkurRd-PeeenyaJunc", "TumkurRdPaperMillJunc",
    "UrvashiJunction", "VBhattRoadJunc", "VVPuramCircle",
    "VaniVilas Hospital", "VidhanaVeedhiJunc", "VijayanagarcircleJunc",
    "VijaynagarCircleJunc", "VisweshwarapuramJunc", "WhitefieldJunc",
    "YelahankaCrossJunc", "YelahankaNKCircle", "YeshwanthapurCircle",
    "YeshwantpurcircleJunc",
]

POLICE_STATIONS = [
    "Adugodi", "Ashok Nagar", "Banashankari", "Banaswadi", "Basavanagudi",
    "Bellandur", "Byatarayanapura", "Chamarajpet", "Chikkabanavara",
    "Chikkajala", "City Market", "Cubbon Park", "Devanahalli Airport",
    "Electronic City", "HAL Old Airport", "HSR Layout", "Halasur",
    "Halasuru Gate", "Hebbala", "Hennuru", "High ground", "Hulimavu",
    "J.P. Nagar", "Jalahalli", "Jayanagara", "Jeevanbheemanagar",
    "Jnanabharathi", "K.G. Halli", "K.R. Pura", "K.S. Layout",
    "Kamakshipalya", "Kengeri", "Kodigehalli", "Madiwala", "Magadi Road",
    "Mahadevapura", "Malleshwaram", "Mico Layout", "Peenya",
    "Pulikeshinagar(F.Town)", "R.T. Nagar", "Rajajinagar", "Sadashivanagar",
    "Sheshadripuram", "Shivajinagar", "Thalagattapura", "Upparpet",
    "V.V.Puram (C.Pet)", "Vijayanagara", "Whitefield", "Wilson Garden",
    "Yelahanka", "Yeshwanthpura",
]

EVENT_CAUSE_MAP = {
    "Political Rally": "procession",
    "Festival / Procession": "procession",
    "Sports Event": "public_event",
    "VIP Movement": "vip_movement",
    "Construction": "construction",
    "Protest": "protest",
    "Accident": "accident",
    "Vehicle Breakdown": "vehicle_breakdown",
    "Water Logging": "water_logging",
    "Tree Fall": "tree_fall",
    "Road Conditions": "road_conditions",
    "Other": "others",
}

EVENT_TYPE_MAP = {
    "Political Rally": "planned",
    "Festival / Procession": "planned",
    "Sports Event": "planned",
    "VIP Movement": "planned",
    "Construction": "planned",
    "Protest": "unplanned",
    "Accident": "unplanned",
    "Vehicle Breakdown": "unplanned",
    "Water Logging": "unplanned",
    "Tree Fall": "unplanned",
    "Road Conditions": "unplanned",
    "Other": "unplanned",
}

# ── Junction Coordinates ───────────────────────────────────────────────────
# Real geographic coordinates for the main traffic junctions in Bengaluru
JUNCTION_COORDS = {
    "MekhriCircleJunc": {"lat": 13.0142, "lng": 77.5831},
    "HebbalFlyoverJunc": {"lat": 13.0358, "lng": 77.5975},
    "TinFactoryJunc": {"lat": 12.9880, "lng": 77.6620},
    "KRCircleJunc": {"lat": 12.9716, "lng": 77.5946},
    "MajesticJunc": {"lat": 12.9779, "lng": 77.5729},
    "PeenyaJunc": {"lat": 13.0315, "lng": 77.5337},
    "NayandahalliJunc": {"lat": 12.9550, "lng": 77.5320},
    "BanashankariBusStandJunc": {"lat": 12.9156, "lng": 77.5736},
    "SilkBoardJunc": {"lat": 12.9176, "lng": 77.6224},
    "DairyCircleJunc": {"lat": 12.9427, "lng": 77.6047},
    "KoramangalaJunc": {"lat": 12.9347, "lng": 77.6189},
    "WhitefieldJunc": {"lat": 12.9698, "lng": 77.7499},
    "YelahankaCrossJunc": {"lat": 13.1000, "lng": 77.5960},
    "AirportJunc": {"lat": 13.1300, "lng": 77.6100},
}

# ── Corridor Connections ────────────────────────────────────────────────────
# Defines the start and end junctions for each of the 21 corridors in static data
CORRIDOR_CONNECTIONS = {
    "Airport New South Road": {"start": "HebbalFlyoverJunc", "end": "TinFactoryJunc"},
    "Bannerghata Road": {"start": "BanashankariBusStandJunc", "end": "DairyCircleJunc"},
    "Bellary Road 1": {"start": "MekhriCircleJunc", "end": "HebbalFlyoverJunc"},
    "Bellary Road 2": {"start": "HebbalFlyoverJunc", "end": "YelahankaCrossJunc"},
    "CBD 1": {"start": "MekhriCircleJunc", "end": "KRCircleJunc"},
    "CBD 2": {"start": "KRCircleJunc", "end": "MajesticJunc"},
    "Hennur Main Road": {"start": "MekhriCircleJunc", "end": "TinFactoryJunc"},
    "Hosur Road": {"start": "DairyCircleJunc", "end": "SilkBoardJunc"},
    "IRR(Thanisandra road)": {"start": "MekhriCircleJunc", "end": "TinFactoryJunc"},
    "Magadi Road": {"start": "MajesticJunc", "end": "NayandahalliJunc"},
    "Mysore Road": {"start": "NayandahalliJunc", "end": "MajesticJunc"},
    "ORR East 1": {"start": "TinFactoryJunc", "end": "KoramangalaJunc"},
    "ORR East 2": {"start": "KoramangalaJunc", "end": "SilkBoardJunc"},
    "ORR North 1": {"start": "HebbalFlyoverJunc", "end": "TinFactoryJunc"},
    "ORR North 2": {"start": "PeenyaJunc", "end": "HebbalFlyoverJunc"},
    "ORR West 1": {"start": "BanashankariBusStandJunc", "end": "SilkBoardJunc"},
    "Old Airport Road": {"start": "KRCircleJunc", "end": "KoramangalaJunc"},
    "Old Madras Road": {"start": "KRCircleJunc", "end": "TinFactoryJunc"},
    "Tumkur Road": {"start": "PeenyaJunc", "end": "MekhriCircleJunc"},
    "Varthur Road": {"start": "TinFactoryJunc", "end": "WhitefieldJunc"},
    "West of Chord Road": {"start": "PeenyaJunc", "end": "NayandahalliJunc"},
}

